### ISSUE TITLE
SIGSEGV occasionally occurs when calling vmaVirtualFree with TLSF algorithm

### ISSUE THREAD

**Issue by AdamYuan** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#230]
Hi.
I am implementing a mesh streaming system using the virtual allocation feature. With the default algorithm, everything works fine. But when I enabled **VMA_VIRTUAL_BLOCK_CREATE_TLSF_ALGORITHM_BIT** in virtual block creation, crashes occasionally occurs in **vmaVirtualFree**. 
I tested it multiple times, and found the crashes all take place in **VmaBlockMetadata_TLSF::InsertFreeBlock** (line 10341), and **block->NextFree()** seems to be an invalid pointer (not null) which cause statement "**block->NextFree()->PrevFree() = block;**" to crash. Further more there might be some errors maintaining **VmaBlockMetadata_TLSF::m_FreeList** since **block->NextFree()** is from it. I hope the information can be of help.
The commit I use is 05d0c89 (the latest at the time). And I'm sure all the virtual block usage is protected by a mutex.

**Comment by adam-sawicki-a** [comment]
Hi,
Do you have `VMA_ASSERT` defined to something that would report failures? Can you please also enable `VMA_HEAVY_ASSERT` and check if you can find something with it? That would help to find the bug.

**Comment by AdamYuan** [comment]
I tried, in Debug mode, with VMA_HEAVY_ASSERT macro enabled. Sadly no failed assertion occurs.

**Comment by adam-sawicki-a** [comment]
Could you please somehow dump the sequence of allocations and frees you do in the virtual block, e.g. to some log or CSV file?

Are you sure you are not passing to `vmaVirtualFree` some uninitialized or already freed allocation handle?

**Comment by AdamYuan** [comment]
```c++
// vma_test_simple.cpp
#define VMA_IMPLEMENTATION
#include "vk_mem_alloc.h"

VmaVirtualBlock block{VK_NULL_HANDLE};

int main() {
	{
		VmaVirtualBlockCreateInfo info = {};
		info.flags = VMA_VIRTUAL_BLOCK_CREATE_TLSF_ALGORITHM_BIT;
		info.size = 50331648;
		vmaCreateVirtualBlock(&info, &block);
	}
	{
		VmaVirtualAllocationCreateInfo info = {};
		info.alignment = 2;
		info.flags = VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT;

		VmaVirtualAllocation allocation[3] = {};

		info.size = 576;
		assert(vmaVirtualAllocate(block, &info, allocation + 0, nullptr) == VK_SUCCESS);
		assert(allocation[0] != VK_NULL_HANDLE);

		info.size = 648;
		assert(vmaVirtualAllocate(block, &info, allocation + 1, nullptr) == VK_SUCCESS);
		assert(allocation[1] != VK_NULL_HANDLE);

		vmaVirtualFree(block, allocation[0]);

		info.size = 720;
		assert(vmaVirtualAllocate(block, &info, allocation + 2, nullptr) == VK_SUCCESS); // where the segfault occurs
		assert(allocation[2] != VK_NULL_HANDLE);
	}
	return 0;
}
```
I found a simple example of this bug.
Compiled with **g++ vma_test_simple.cpp -lvulkan**, the code produces a segfault

**Comment by AdamYuan** [comment]
I also accidentally discovered another bug: when using default algorithm, the allocation object can be null even if vmaVirtualAllocate succeed
```c++
#define VMA_IMPLEMENTATION
#include "vk_mem_alloc.h"

VmaVirtualBlock block{VK_NULL_HANDLE};

int main() {
	{
		VmaVirtualBlockCreateInfo info = {};
		info.size = 134217728;
		assert(vmaCreateVirtualBlock(&info, &block) == VK_SUCCESS);
		assert(block != VK_NULL_HANDLE);
	}
	{
		VmaVirtualAllocationCreateInfo info = {};
		info.alignment = 8;
		info.flags = VMA_VIRTUAL_ALLOCATION_CREATE_STRATEGY_MIN_MEMORY_BIT;

		VmaVirtualAllocation allocation;

		info.size = 1536;
		assert(vmaVirtualAllocate(block, &info, &allocation, nullptr) == VK_SUCCESS);
		assert(allocation != VK_NULL_HANDLE); // VK_SUCCESS but allocation is null
	}
	return 0;
}
```

**Comment by adam-sawicki-a** [comment]
Thank you for the repro, we will investigate it.

Regarding the other bug, we just fixed it today. Please check the latest code and see if it is fine now - `VK_NULL_HANDLE` should never happen for a successful allocation in the default or linear algorithm.

**Comment by adam-sawicki-a** [comment]
In your first code sample, please note you are calling functions with side-effects inside `assert`. If the program is not compiled in some Debug mode, this code is not executed.

I pushed fixes to the library so that calling `vmaVirtualFree` for `allocation == VK_NULL_HANDLE` is legal and does nothing.

**Comment by AdamYuan** [comment]
Well, after some test, I believe the bug still exist.
I add a assertion in the vma header as followed:
``` c++
void VmaBlockMetadata_TLSF::InsertFreeBlock(Block* block)
{
    // ...
    uint32_t index = GetListIndex(memClass, secondIndex);
    VMA_ASSERT(index < m_ListsCount); // THE ASSERTION
    block->PrevFree() = VMA_NULL; // Line 10342
    block->NextFree() = m_FreeList[index];
    m_FreeList[index] = block;
    if (block->NextFree() != VMA_NULL)
    // ...
```
And in the example code (compiled in debug mode)
``` c++
#define VMA_IMPLEMENTATION
#include "vk_mem_alloc.h"

#include <cstdio>
#include <cstdlib>

VmaVirtualBlock block{VK_NULL_HANDLE};

int main() {
	{
		VmaVirtualBlockCreateInfo info = {};
		info.flags = VMA_VIRTUAL_BLOCK_CREATE_TLSF_ALGORITHM_BIT;
		info.size = 50331648;
		vmaCreateVirtualBlock(&info, &block);
	}
	{
		VmaVirtualAllocationCreateInfo info = {};
		info.alignment = 2;

		VmaVirtualAllocation allocation[3] = {};

		info.size = 576;
		vmaVirtualAllocate(block, &info, allocation + 0, nullptr);

		info.size = 648;
		vmaVirtualAllocate(block, &info, allocation + 1, nullptr);

		vmaVirtualFree(block, allocation[0]);

		info.size = 720;
		vmaVirtualAllocate(block, &info, allocation + 2, nullptr);
	}
	return 0;
}
```
the assertion fails, which indicates there are surely some memory access errors.
