### ISSUE TITLE
Possible race condition on VmaAllocator between defragmentation and regular allocations

### ISSUE THREAD

**Issue by sbourasse** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#313]
We've been using VMA extensively for our memory management on projects with heavy memory load. However, upon integrating the defragmentation utility, we started getting frequent memory corruption on internal VMA data. We narrowed down the source of this corruption to concurrent accesses on our `VmaAllocator` and (apparently) succeeded in preventing it by blocking allocations for the duration of the defragmentation. More context follows, with a couple questions at the end.

We use a single `VmaAllocator` from two separate threads. Most of our allocations are done from the rendering thread, which is also the one that runs the defragmentation. We also allocate from the main thread, although less frequently.

Our defragmentation integration looks something like this (it has the same structure as what can be found in the online documentation) :
```
vmaBeginDefragmentation(mainAllocator, ...);

for (;;)
{
	if (vmaBeginDefragmentationPass(mainAllocator, ...) == VK_SUCCESS)
	   break;

	CreateResourcesAndCopy();
	WaitForCompletion();

	if (vmaEndDefragmentationPass(mainAllocator, ...) == VK_SUCCESS)
		break;
}

vmaEndDefragmentation(mainAllocator, ...);
```

Running this bit of code on heavy workloads from our rendering thread while our main thread is free to use `mainAllocator` for other allocations, we reliably trigger memory corruptions, specifically located on the first 4 bytes of random `VmaAllocation` from our working `VmaDefragmentationPassMoveInfo::pMoves` array.

Regardless of this particular symptom, we managed to prevent such corruption by implementing a mutex targeting the region between `vmaBeginDefragmentation()` and `vmaEndDefragmentation()` as well as other VMA calls on `mainAllocator`, specifically those that could be made concurrently to defragmentation.

As a side note, we first prevented memory corruption by enabling `VMA_DEBUG_GLOBAL_MUTEX`, changing `VmaMutex::m_Mutex` type to `std::recursive_mutex`, and locking it from our side right after `vmaBeginDefragmentation()` and releasing it right before `vmaEndDefragmentation()`.

Does it make sense to treat the region from `vmaBeginDefragmentation()` to `vmaEndDefragmentation()` as a critical section with regards to the used `VmaAllocator` ? If so, is it something that could be enforced from within the library ?

**Comment by adam-sawicki-a** [comment]
Thank you for reporting this bug and a good description. It sounds very serious. We will investigate it. Any help in debugging it is welcome.

Blocking any usage of the allocator between Begin and EndDefragmentation may be a good workaround for the bug, but it shouldn't be needed. Defragmentation was developed with the assumption that using the allocator while defragmentation is in progress is allowed.

Is your code 32- or 64-bit?

**Comment by sbourasse** [comment]
We triggered this issue on x86-64 with an AMD GPU.
We can definitely lend a hand with debugging, just let me know what we can do.

**Comment by CannibalVox** [comment]
Forgive me if I'm wrong, but I've been looking at the defrag code recently and the map transferring code seems really sketchy to me.

* There's a period of time after the allocation data swap but before maps are transferred to the new block when an allocation thinks it has references to a block but doesn't (unmapping during this period of time can cause explosions or cause the reference count to underflow)
* Copies to the new memory can occur while the same memory is being written elsewhere. Results vary based on memory type
* New maps can be opened on memory that's already been copied to the new location but before the allocation swap, resulting in a write that isn't actually going to be used. It's possible for the block to be fully unmapped or freed by the defragmenter while this is happening.

It just seems like from a logical standpoint, from the moment the copy begins to the end of the pass, a memory block being moved needs to be unwritable. More generally, the VMA documentation says that allocations are not considered thread safe, and the defrag manipulates them.  

Am I wrong here?

**Comment by IAmNotHanni** [comment]
Once we have ported VulkanSample app to Linux (https://github.com/GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator/issues/466), we could compile it with clang using the `-fsanitize=thread` flag. [Clang's thread sanitizer](https://clang.llvm.org/docs/ThreadSanitizer.html) is a very advanced tool and catches a ton of issues related to parallelization problems. I just also realized that there's clang for Windows, which can be installed easily through Visual Studio Installer. Maybe this flag is available on clang for Windows as well, which could be a great help in analyzing a possible data race.

**Comment by danginsburg** [comment]
I am not sure if I'm hitting precisely the same issue here, but thought I'd mention - we have a very hard-to-repro crash with defrag (which we more or less run continuously in Source 2).  On occasion, when looping over the `VmaDefragmentationMove` s that are returned, we get one where `pMove->srcAllocation->GetBlock()` is nullptr.  This causes a crash when we call `vmaGetAllocationInfo` on `pMove->srcAllocation`.  The callstack looks like this:

```
rendersystemvulkan.dll!VmaAllocation_T::GetOffset+0x2e 
rendersystemvulkan.dll!VmaAllocator_T::GetAllocationInfo+0x79 
rendersystemvulkan.dll!CMemoryManagerVulkan::VmaUpdateDefragMainThread
...
```

I'm unfortunately not able to provide a reproducer case.

**Comment by danginsburg** [comment]
Attached is a standalone reproducer case.  On Windows with VS2022 I built and ran the attached case in the debugger (RelWithDebInfo).  If you let it run for long enough, you end up with a very similar crash to what we are seeing in our engine:

```
>	vma_race_test.exe!VmaAllocation_T::GetMemory() Line 11251	C++
 	vma_race_test.exe!VmaAllocator_T::GetAllocationInfo(VmaAllocation_T * hAllocation, VmaAllocationInfo * pAllocationInfo) Line 14657	C++
 	vma_race_test.exe!defrag_thread() Line 358	C++
 	[Inline Frame] vma_race_test.exe!std::invoke(void(*)() &&) Line 1695	C++
 	vma_race_test.exe!std::thread::_Invoke<std::tuple<void (__cdecl*)(void)>,0>(void * _RawVals) Line 61	C++
 	ucrtbase.dll!thread_start<unsigned int (__cdecl*)(void *),1>()	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown

Exception thrown: read access violation.
this->m_BlockAllocation.**m_Block** was 0x2B000000052.
```

[vma_race_test.zip](https://github.com/user-attachments/files/23100611/vma_race_test.zip)

**Comment by turol** [comment]
I ran your testcase under ThreadSanitizer. Here's the log: https://gist.github.com/turol/d1d808e24f34f826cc0dd0d26cb2a915

Findings:
1. Nvidia's driver is not compatible with tsan. This log is from Raspberry Pi.
2. You're accessing `allocations.size()` without synchronizing. This is probably benign.
3. The race between `IncrementallySortBlocks / SetIncrementalSort` is also probably benign but should be fixed.
4. The race between `VmaBlockMetadata_TLSF::GetSumFreeSize / VmaBlockMetadata_TLSF::InsertFreeBlock` looks like it might be the actual issue.

**Comment by sawickiap** [comment]
I merged a fix for the race condition in defragmentation, on my fork for now:
https://github.com/sawickiap/VulkanMemoryAllocator
Please let me know if it fixes the problem.

**Comment by danginsburg** [comment]
> Please let me know if it fixes the problem.

Funny, I made an exactly identical fix to try fix this problem locally in our copy.  The frequency of the crash has definitely gone down but I'm not confident it totally fixes it because I still see it crash occasionally in `vmaGetAllocationInfo`/ I've still managed to get ThreadSanitizer warnings with it using the test program above that I wasn't able to figure out a clean fix for.

<img width="1181" height="1130" alt="Image" src="https://github.com/user-attachments/assets/f2d6f5d7-0107-46bd-8e10-143c831c959f" />

**Comment by JustSid** [comment]
@danginsburg oh sweet! I have to admit, I did a total stab in the dark here because my Linux install is very unhappy with TSAN, so I based this only on our debug sort assertions and @turol's TSAN log (and prayer).

It sounds like the repro works nicely with TSAN on a Raspberry Pi though, so I might give that a try and see what else comes up.

**Comment by JustSid** [comment]
Sorry, I dropped this a bit. But I did some more digging, just like @danginsburg we also still see crashes in production. I ended up in `VmaDefragmentationContext_T::DefragmentPassEnd`, in the `VMA_DEFRAGMENTATION_MOVE_OPERATION_COPY` case where `SwapBlockAllocation()` gets called without the vector lock being held and it then mutates the free list of the block by calling `SetAllocationUserData()` (the user data and next linked list pointer is unioned). 

I haven't thrown this at our users yet, so I don't know if it makes a dent, but at least from my understanding of the code this could reasonably race and lead to corrupted meta data. I thought I bring it up here to see if those findings make sense or if I'm an idiot. Sorry, the VMA source code is almost as dense as I am and my IDE struggles with navigating it, so I could be completely off here 😅

**Comment by JustSid** [comment]
[vk_mem_alloc.patch](https://github.com/user-attachments/files/27782138/vk_mem_alloc.patch)

This is the missing lock that should protect the free list

**Comment by sawickiap** [comment]
Thank you for finding this fix. I merged it into my fork for now:
https://github.com/sawickiap/VulkanMemoryAllocator

Does it fix the problem for you?

**Comment by danginsburg** [comment]
@JustSid - thanks I'm going to try this patch in our code too.  For what it's worth, I have still continued to see the crashes with just my fixes (although less frequent) so perhaps your additional fix is the final boss.  I'll let you know when I've had some more testing on it.

**Comment by JustSid** [comment]
> Does it fix the problem for you?

I'm afraid the jury is still out, we haven't put this into a release yet. Although we are in the process of releasing a bigger update soon and I'm hoping to get it into the next beta release vehicle. I'll also report back once I have actual crash data from the field.

**Comment by danginsburg** [comment]
Following up: we've been running with the latest patch from @JustSid for about 3 weeks.  It did seem to decrease the frequency of the crashes but they are still happening.  So I don't think the issue is fully fixed.

**Comment by sawickiap** [comment]
Thank you for the continued testing. I found and pushed another synchronization fix to the latest master of my fork:

https://github.com/sawickiap/VulkanMemoryAllocator

The remaining problem was in `DefragmentPassEnd` for the `EXTENSIVE` algorithm. Block counts were sampled around `VmaBlockVector::Free()` using separate lock scopes, and the block vector was later accessed without its mutex. Concurrent allocations could therefore produce invalid defragmentation state.

The fix now obtains the released-block information while the vector is locked and synchronizes the remaining block access.
Please note that this specifically affects `EXTENSIVE` when the `bufferImageGranularity` is greater than 1. Please try the latest version and let me know whether it improves the situation.

**Comment by danginsburg** [comment]
Thanks for continuing to follow up @sawickiap as we continued to be plagued by intermittent crashes with defrag.  Unfortunately, we use `VMA_DEFRAGMENTATION_FLAG_ALGORITHM_BALANCED_BIT` so it appears your fix won't fix our issue, but I will take your patch and can report back.  If there is any additional information I could provide that would help the investigation, please let me know.

**Comment by JustSid** [comment]
We use `VMA_DEFRAGMENTATION_FLAG_ALGORITHM_FULL_BIT` and still see the occasional crash as well. Sadly I haven't had much time to investigate this much further yet.
