### ISSUE TITLE
error: use of undeclared identifier 'LARGE_INTEGER' on Windows clang 6.0

### ISSUE THREAD

**Issue by farnoy** [GPUOpen-LibrariesAndSDKs/VulkanMemoryAllocator#38]
Hi, I'm getting this error when building a `2.1.0-beta.1` with this configuration:
```cpp
#define VMA_IMPLEMENTATION
#define VMA_STATIC_VULKAN_FUNCTIONS 0
#include "vk_mem_alloc.h"
```

When using clang version:
```
clang version 6.0.0 (tags/RELEASE_600/final)
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Program Files\LLVM\bin
```

I traced this problem to the new recording functionality, adding `#define VMA_RECORDING_ENABLED 0` takes care of the problem.

Full output from clang:

```
>clang++ --std=c++14 amd_alloc.cc -c -o amd_alloc.o -g -IC:\VulkanSDK\1.1.82.0\Include
In file included from amd_alloc.cc:4:
In file included from ./wrapper.h:1:
./vendor/VulkanMemoryAllocator/src/vk_mem_alloc.h:10470:32: error: use of undeclared identifier 'LARGE_INTEGER'
    QueryPerformanceFrequency((LARGE_INTEGER*)&m_Freq);
                               ^
./vendor/VulkanMemoryAllocator/src/vk_mem_alloc.h:10470:46: error: expected expression
    QueryPerformanceFrequency((LARGE_INTEGER*)&m_Freq);
                                             ^
./vendor/VulkanMemoryAllocator/src/vk_mem_alloc.h:10471:30: error: use of undeclared identifier 'LARGE_INTEGER'
    QueryPerformanceCounter((LARGE_INTEGER*)&m_StartCounter);
                             ^
./vendor/VulkanMemoryAllocator/src/vk_mem_alloc.h:10471:44: error: expected expression
    QueryPerformanceCounter((LARGE_INTEGER*)&m_StartCounter);
                                           ^
./vendor/VulkanMemoryAllocator/src/vk_mem_alloc.h:10908:26: error: use of undeclared identifier 'GetCurrentThreadId'
    outParams.threadId = GetCurrentThreadId();
                         ^
./vendor/VulkanMemoryAllocator/src/vk_mem_alloc.h:10910:5: error: unknown type name 'LARGE_INTEGER'
    LARGE_INTEGER counter;
    ^
6 errors generated.
```

**Comment by EvanL1719** [comment]
I'm getting the same problem as well, the problem does not exist for the v2.0.0 release.

**Comment by adam-sawicki-amd** [comment]
Thank you for finding this issue. I think this isn't about clang, but rather about missing `#include <Windows.h>` when using VMA on Windows without macro `VK_USE_PLATFORM_WIN32_KHR` defined. I pushed a fix to "development" branch. Can you please test it and see if it helps?

**Comment by EvanL1719** [comment]
I just pulled your fix and tried compiling, but the same errors still persist.

**Comment by farnoy** [comment]
Hey @adam-sawicki-amd,

You need to make two changes:
1) move up the `#ifndef VMA_RECORDING_ENABLED` block above the block that conditionally includes `Windows.h`
2) add a `#define NOMINMAX` before including `Windows.h`

Git patch based on 447e36fe9ae6eaedbeebdf49f73dcdd5316c26bb

```diff
diff --git a/src/vk_mem_alloc.h b/src/vk_mem_alloc.h
index de83405..64e9bd6 100644
--- a/src/vk_mem_alloc.h
+++ b/src/vk_mem_alloc.h
@@ -1359,7 +1359,20 @@ Features deliberately excluded from the scope of this library:

 #include <vulkan/vulkan.h>

+/*
+Define this macro to 0/1 to disable/enable support for recording functionality,
+available through VmaAllocatorCreateInfo::pRecordSettings.
+*/
+#ifndef VMA_RECORDING_ENABLED
+    #ifdef _WIN32
+        #define VMA_RECORDING_ENABLED 1
+    #else
+        #define VMA_RECORDING_ENABLED 0
+    #endif
+#endif
+
 #if VMA_RECORDING_ENABLED
+    #define NOMINMAX
     #include <Windows.h>
 #endif

@@ -1483,18 +1496,6 @@ typedef enum VmaRecordFlagBits {
 } VmaRecordFlagBits;
 typedef VkFlags VmaRecordFlags;

-/*
-Define this macro to 0/1 to disable/enable support for recording functionality,
-available through VmaAllocatorCreateInfo::pRecordSettings.
-*/
-#ifndef VMA_RECORDING_ENABLED
-    #ifdef _WIN32
-        #define VMA_RECORDING_ENABLED 1
-    #else
-        #define VMA_RECORDING_ENABLED 0
-    #endif
-#endif
-
 /// Parameters for recording calls to VMA functions. To be used in VmaAllocatorCreateInfo::pRecordSettings.
 typedef struct VmaRecordSettings
 {
```

**Comment by farnoy** [comment]
One might say that you need the first change so that the value of `VMA_RECORDING_ENABLED`  is _uniform_  across the whole translation unit. 😉😉

**Comment by rextimmy** [comment]
If NOMINMAX is going to be added to VMA, it would be best to check first if it is already defined, a lot of projects already define this one themselves.

**Comment by adam-sawicki-amd** [comment]
How about now? Is the problem solved after latest push to "development" branch.

**Comment by adam-sawicki-amd** [comment]
Did the fix (now also merged to "master" branch) solve the issue?

**Comment by adam-sawicki-amd** [comment]
I assume the problem is solved.
